# Generated by Django 2.2.5 on 2019-09-22 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=256)),
            ],
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='estado_civil',
            field=models.CharField(choices=[('1', 'Soltero/a'), ('2', 'Casado/a'), ('3', 'Separado/a de hecho'), ('4', 'Viudo/a'), ('5', 'Divorciado/a'), ('6', 'Unido/a de Hecho')], max_length=32),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='familia',
            field=models.ManyToManyField(to='estudiantes.Familiar'),
        ),
    ]
